[package]
name = "polkavm-wasm-compiler"
version = "0.3.2-rc.4"
edition = "2021"
description = "Host-independent PolkaVM bytecode to WebAssembly compiler"
license = "MPL-2.0"
repository = "https://github.com/paritytech/polkavm-host-runtime"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
polkavm-common = { git = "https://github.com/paritytech/polkavm.git", rev = "642fa95a6f1df85612bdbd0a7e4353a2aa4dc9b5", version = "=0.37.0", default-features = false, features = ["alloc"] }
wasm-encoder = "0.240"

[dev-dependencies]
polkavm = { git = "https://github.com/paritytech/polkavm.git", rev = "642fa95a6f1df85612bdbd0a7e4353a2aa4dc9b5", version = "=0.37.0", features = ["generic-sandbox"] }
wasmi = "0.40"
wasmparser = "0.240"
